### ISSUE TITLE
Add Params for .gfx generation

### ISSUE THREAD

**Issue by BlueIronLabs** [Flone-dnb/cryengine-ui-helper#1]
It would be awesome to be able to specify params for gfx generation. There are options like `-qh -share_images` that would be great to be able to do from this UI.

**Comment by Flone-dnb** [comment]
You can specify additional parameters for .gfx generation using the `Additional GFxExport arguments` field (see attached screenshot).

![Untitled](https://user-images.githubusercontent.com/37961576/198525837-3b783418-927a-4f29-b79c-c89913315c77.png)

Have you tried this?

**Comment by BlueIronLabs** [comment]
You are absolutely correct, and I completely overlooked this. Nice!
